# Generated by Django 4.1.3 on 2022-12-01 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_tag_rent_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent',
            name='tags',
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(to='accounts.tag'),
        ),
    ]
