# Generated by Django 4.1.3 on 2022-12-05 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='carname',
            new_name='manufacturer',
        ),
    ]
