# Generated by Django 4.1.3 on 2022-12-05 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_carname_product_manufacturer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rent',
            old_name='Customer',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='rent',
            old_name='Product',
            new_name='product',
        ),
    ]
