# Generated by Django 4.1.3 on 2022-12-05 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_customer_rent_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='status',
            field=models.CharField(choices=[('Rented', 'Rented'), ('Avaiable', 'Avaiable')], default='Avaiable', max_length=200),
        ),
    ]
